---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Updating apt
      command: apt-get update

    - name: Install Docker
      command: apt-get install -y docker.io

    - name: Start Docker Service
      command: systemctl start docker

    - name: Stop old container if exists
      command: docker rm -f healthcare-container
      ignore_errors: yes

    - name: Deploy Docker Container
      command: docker run -itd --name healthcare-container -p 8082:8082 king094/healthcare-project:v1.0.0
