---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-container
          image: healthcare-project:v1.0.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare
spec:
  selector:
    app: healthcare
  type: LoadBalancer
  ports:
    - port: 8082         # External port
      targetPort: 8080   # Match containerPort
      protocol: TCP
