---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-container
          image: king094/healthcare-project:v1.0.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: healthcare
spec:
  selector:
    app: healthcare
  type: NodePort
  ports:
    - nodePort: 31010
      port: 8082           
      targetPort: 8082    
      nodePort: 31010       
      protocol: TCP
